export default {
  name: 'sttr_2020',
  icon: 'radar-chart',
  defaultLayout: {
    lg: [
      {
        i: 'satellite-simple-testpage-a',
        x: 0,
        y: 0,
        w: 3,
        h: 7,
        component: {
          name: 'AgentList',
        },
      },

      {
        i: 'satellite-simple-testpage-o',
        x: 3,
        y: 0,
        w: 7,
        h: 18,
        component: {
          name: 'Globe',
          props: {
            name: 'Orbit',
            orbits: [
              {
                name: 'mothership',
                modelFileName: '',
                nodeProcess: 'mothership:mother',
                //XDataKey: 'node.loc.pos.eci.s',
                XDataKey: 'my_state',
                YDataKey: 'my_state',
                ZDataKey: 'my_state',
                processXDataKey: (x) => x.x_pos,
                processYDataKey: (x) => x.y_pos,
                processZDataKey: (x) => x.z_pos,
				//dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [1, 1, 1],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
			  {
                name: 'daughter_01',
                modelFileName: '',
                nodeProcess: 'daughter_01:allison',
                //XDataKey: 'node.loc.pos.eci.s',
				XDataKey: 'my_state',
                YDataKey: 'my_state',
                ZDataKey: 'my_state',
                processXDataKey: (x) => x.x_pos,
                processYDataKey: (x) => x.y_pos,
                processZDataKey: (x) => x.z_pos,
				//dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [1, 1, 1],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
			  {
                name: 'daughter_02',
                modelFileName: '',
                nodeProcess: 'daughter_02:becky',
                //XDataKey: 'node.loc.pos.eci.s',
                XDataKey: 'my_state',
                YDataKey: 'my_state',
                ZDataKey: 'my_state',
                processXDataKey: (x) => x.x_pos,
                processYDataKey: (x) => x.y_pos,
                processZDataKey: (x) => x.z_pos,
				//dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [1, 1, 1],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
			  {
                name: 'daughter_03',
                modelFileName: '',
                nodeProcess: 'daughter_03:cecilia',
                //XDataKey: 'node.loc.pos.eci.s',
                XDataKey: 'my_state',
                YDataKey: 'my_state',
                ZDataKey: 'my_state',
                processXDataKey: (x) => x.x_pos,
                processYDataKey: (x) => x.y_pos,
                processZDataKey: (x) => x.z_pos,
				//dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [1, 1, 1],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },
			  {
                name: 'daughter_04',
                modelFileName: '',
                nodeProcess: 'daughter_04:delilah',
                //XDataKey: 'node.loc.pos.eci.s',
                XDataKey: 'my_state',
                YDataKey: 'my_state',
                ZDataKey: 'my_state',
                processXDataKey: (x) => x.x_pos,
                processYDataKey: (x) => x.y_pos,
                processZDataKey: (x) => x.z_pos,
				//dataKey: 'node_loc_pos_eci',
                timeDataKey: 'node_utc',
                live: true,
                position: [1, 1, 1],
                orientation: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
              },

            ],
            overlays: [],
          },
        },
      },

      {
        i: 'satellite-simple-testpage-gps-a',
        x: 0,
        y: 7,
        w: 3,
        h: 7,
        component: {
          name: 'DisplayValue',
          props: {
            name: 'Mechanics',
            displayValues: [
              {
                name: 'x_pos',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.x_pos),
                live: true,
              },
			  {
                name: 'y_pos',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.y_pos),
                live: true,
              },
			  {
                name: 'z_pos',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.z_pos),
                live: true,
              },
			  {
                name: 'x_vel',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.x_vel),
                live: true,
              },
			  {
                name: 'y_vel',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.y_vel),
                live: true,
              },
			  {
                name: 'z_vel',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.z_vel),
                live: true,
              },
			  {
                name: 'x_acc',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.x_acc),
                live: true,
              },
			  {
                name: 'y_acc',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.y_acc),
                live: true,
              },
			  {
                name: 'z_acc',
                nodeProcess: 'mothership:mother',
                dataKey: 'my_state',
                timeDataKey: 'node_utc',
                unit: 'm',
                processDataKey: (x) => JSON.stringify(x.z_acc),
                live: true,
              },
              
            ],
          },
        },
      },
      {
        i: 'satellite-simple-testpage-command',
        x: 0,
        y: 20,
        w: 10,
        h: 15,
        component: {
          name: 'Commands',
          props: { nodes: ['test'] },
        },
      },
	  {
        i: 'satellite-simple-test-att',
        x: 0,
        y: 35,
        w: 6,
        h: 21,
        component: {
          name: 'Attitude',
          props: {
            name: 'Attitude',
            attitudes: [
              {
                name: 'mothership',
                nodeProcess: 'mothership:exec',
                dataKey: 'node_loc_att_icrf',
                quaternions: {
                  d: {
                    x: 0,
                    y: 0,
                    z: 0,
                  },
                  w: 0,
                },
                live: true,
              },
            ],
          },
        },
      },

    ],
  },
};
