import {
  mjdToUTCString,
} from '../../../utility/time';

export default {
  lg: [
    {
      i: 'satellite-neutron1-espsp-x',
      x: 0,
      y: 1,
      w: 1,
      h: 14,
      component: {
        name: 'Image',
        props: {
          node: 'neutron1',
          name: 'Solar Panel Z- (BCR0)',
          file: 'Solar-Panel--Z.png',
        },
      },
    },
    {
      i: 'satellite-neutron1-espsp-ax',
      x: 1,
      y: 1,
      w: 1,
      h: 14,
      component: {
        name: 'Image',
        props: {
          node: 'neutron1',
          name: 'Solar Panel Z+ (BCR1)',
          file: 'Solar-Panel-+Z.png',
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-a',
      x: 2,
      y: 1,
      w: 4,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Panel Z- (BCR0)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_000',
              timeDataKey: 'device_bcreg_utc_000',
              unit: 'A',
              processDataKey: (x) => Math.abs(x.toFixed(4)),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_000',
              timeDataKey: 'device_bcreg_utc_000',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Pwr',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_000',
              timeDataKey: 'device_bcreg_utc_000',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_000',
              timeDataKey: 'device_bcreg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-b',
      x: 2,
      y: 1,
      w: 4,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Panel Z+ (BCR1)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_001',
              timeDataKey: 'device_bcreg_utc_001',
              unit: 'A',
              processDataKey: (x) => x.toFixed(4),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_001',
              timeDataKey: 'device_bcreg_utc_001',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Pwr',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_001',
              timeDataKey: 'device_bcreg_utc_001',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_001',
              timeDataKey: 'device_bcreg_utc_001',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-espsp-cx',
      x: 6,
      y: 1,
      w: 1,
      h: 14,
      component: {
        name: 'Image',
        props: {
          node: 'neutron1',
          name: 'Solar Panel Y+ (BCR3)',
          file: 'Solar-Panel-+Y.png',
        },
      },
    },
    {
      i: 'satellite-neutron1-espsp-bx',
      x: 7,
      y: 1,
      w: 1,
      h: 14,
      component: {
        name: 'Image',
        props: {
          node: 'neutron1',
          name: 'Solar Panel Y- (BCR2)',
          file: 'Solar-Panel--Y.png',
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-c',
      x: 8,
      y: 2,
      w: 4,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Panel Y+ (BCR2)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_002',
              timeDataKey: 'device_bcreg_utc_002',
              unit: 'A',
              processDataKey: (x) => x.toFixed(4),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_002',
              timeDataKey: 'device_bcreg_utc_002',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Pwr',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_002',
              timeDataKey: 'device_bcreg_utc_002',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_002',
              timeDataKey: 'device_bcreg_utc_002',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-d',
      x: 8,
      y: 2,
      w: 4,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Panel Y- (BCR3)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_003',
              timeDataKey: 'device_bcreg_utc_003',
              unit: 'A',
              processDataKey: (x) => x.toFixed(4),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_003',
              timeDataKey: 'device_bcreg_utc_003',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Pwr',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_003',
              timeDataKey: 'device_bcreg_utc_003',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_003',
              timeDataKey: 'device_bcreg_utc_003',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-e',
      x: 0,
      y: 3,
      w: 12,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Solar Panel Current',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'blue',
              },
              name: 'Solar Panel Z- (A)',
              YDataKey: 'device_bcreg_amp_000',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'orange',
              },
              name: 'Solar Panel Z+ (A)',
              YDataKey: 'device_bcreg_amp_001',
              timeDataKey: 'device_bcreg_utc_001',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Y- (A)',
              YDataKey: 'device_bcreg_amp_002',
              timeDataKey: 'device_bcreg_utc_002',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'purple',
              },
              name: 'Solar Panel Y+ (A)',
              YDataKey: 'device_bcreg_amp_003',
              timeDataKey: 'device_bcreg_utc_003',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'cyan',
              },
              name: 'Solar Pwr Supply X- (A)',
              YDataKey: 'device_bcreg_amp_004',
              timeDataKey: 'device_bcreg_utc_004',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'green',
              },
              name: 'Solar Pwr Supply X+ (A)',
              YDataKey: 'device_bcreg_amp_005',
              timeDataKey: 'device_bcreg_utc_005',
              processYDataKey: (x) => Math.abs(x.toFixed(4)),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-f',
      x: 0,
      y: 4,
      w: 12,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Solar Panel Voltage',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'blue',
              },
              name: 'Solar Panel Z- (V)',
              YDataKey: 'device_bcreg_volt_000',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'orange',
              },
              name: 'Solar Panel Z+ (V)',
              YDataKey: 'device_bcreg_volt_001',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Y- (V)',
              YDataKey: 'device_bcreg_volt_002',
              timeDataKey: 'device_bcreg_utc_002',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'purple',
              },
              name: 'Solar Panel Y+ (V)',
              YDataKey: 'device_bcreg_volt_003',
              timeDataKey: 'device_bcreg_utc_003',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'cyan',
              },
              name: 'Solar Pwr Supply X- (V)',
              YDataKey: 'device_bcreg_volt_004',
              timeDataKey: 'device_bcreg_utc_004',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'green',
              },
              name: 'Solar Pwr Supply X+ (V)',
              YDataKey: 'device_bcreg_volt_005',
              timeDataKey: 'device_bcreg_utc_005',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-h',
      x: 0,
      y: 5,
      w: 12,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Solar Panel Pwr',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'blue',
              },
              name: 'Solar Panel Z- (W)',
              YDataKey: 'device_bcreg_power_000',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'orange',
              },
              name: 'Solar Panel Z+ (W)',
              YDataKey: 'device_bcreg_power_001',
              timeDataKey: 'device_bcreg_utc_001',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Y- (W)',
              YDataKey: 'device_bcreg_power_002',
              timeDataKey: 'device_bcreg_utc_002',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Y+ (W)',
              YDataKey: 'device_bcreg_power_003',
              timeDataKey: 'device_bcreg_utc_003',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Pwr Supply X- (W)',
              YDataKey: 'device_bcreg_power_004',
              timeDataKey: 'device_bcreg_utc_004',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Pwr Supply X+ (W)',
              YDataKey: 'device_bcreg_power_005',
              timeDataKey: 'device_bcreg_utc_005',
              processYDataKey: (x) => Math.abs(x.toFixed(2)),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-g',
      x: 0,
      y: 6,
      w: 9,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Solar Panel Temperature',
          defaultRange: 'temperature',
          XDataKey: 'node_utc',
          processXDataKey: (x) => mjdToUTCString(x),
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'blue',
              },
              name: 'Solar Panel Z- (C)',
              YDataKey: 'device_bcreg_temp_000',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'orange',
              },
              name: 'Solar Panel Z+ (C)',
              YDataKey: 'device_bcreg_temp_001',
              timeDataKey: 'device_bcreg_utc_001',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Y- (C)',
              YDataKey: 'device_bcreg_temp_002',
              timeDataKey: 'device_bcreg_utc_002',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'purple',
              },
              name: 'Solar Panel Y+ (C)',
              YDataKey: 'device_bcreg_temp_003',
              timeDataKey: 'device_bcreg_utc_003',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'cyan',
              },
              name: 'Solar Pwr Supply X- (C)',
              YDataKey: 'device_bcreg_temp_004',
              timeDataKey: 'device_bcreg_utc_004',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'green',
              },
              name: 'Solar Pwr Supply X+ (C)',
              YDataKey: 'device_bcreg_temp_005',
              timeDataKey: 'device_bcreg_utc_005',
              processYDataKey: (x) => x,
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-z',
      x: 9,
      y: 6,
      w: 3,
      h: 9,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Pwr Supply X- (BCR4)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_004',
              timeDataKey: 'device_bcreg_utc_004',
              unit: 'A',
              processDataKey: (x) => x.toFixed(4),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_004',
              timeDataKey: 'device_bcreg_utc_004',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Pwr',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_004',
              timeDataKey: 'device_bcreg_utc_004',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_004',
              timeDataKey: 'device_bcreg_utc_004',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-epssp-y',
      x: 9,
      y: 7,
      w: 3,
      h: 9,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Pwr Supply X+ (BCR5)',
          displayValues: [
            {
              name: 'Current',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_amp_005',
              timeDataKey: 'device_bcreg_utc_005',
              unit: 'A',
              processDataKey: (x) => x.toFixed(4),
              live: true,
            },
            {
              name: 'Voltage',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_volt_005',
              timeDataKey: 'device_bcreg_utc_005',
              unit: 'V',
              processDataKey: (x) => x.toFixed(2),
              live: true,
            },
            {
              name: 'Power',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_power_005',
              timeDataKey: 'device_bcreg_utc_005',
              unit: 'W',
              processDataKey: (x) => Math.abs(x.toFixed(2)),
              live: true,
            },
            {
              name: 'Temperature',
              nodeProcess: 'any',
              dataKey: 'device_bcreg_temp_005',
              timeDataKey: 'device_bcreg_utc_005',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
              live: true,
            },
          ],
        },
      },
    },
  ],
};
