export default {
  lg: [
    {
      i: 'satellite-neutron1-thermal-a',
      x: 0,
      y: 0,
      w: 3,
      h: 22,
      component: {
        name: 'Image',
        props: {
          node: 'neutron1',
          name: 'Overview',
          file: 'Overview.png',
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-b',
      x: 3,
      y: 0,
      w: 3,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Battery Temperatures',
          displayValues: [
            {
              name: 'Battery',
              nodeProcess: 'any',
              dataKey: 'device_batt_temp_000',
              timeDataKey: 'device_batt_utc_000',
              dataKeyUpperThreshold: 60,
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'DB 1',
              nodeProcess: 'any',
              dataKey: 'device_tsen_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_tsen_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'DB 2 001',
              nodeProcess: 'any',
              dataKey: 'device_tsen_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_tsen_utc_001',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'DB 2 002',
              nodeProcess: 'any',
              dataKey: 'device_tsen_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_tsen_utc_002',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'DB 2 003',
              nodeProcess: 'any',
              dataKey: 'device_tsen_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_tsen_utc_003',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-c',
      x: 6,
      y: 0,
      w: 3,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'CPU Temperatures',
          displayValues: [
            {
              name: 'BBB',
              nodeProcess: 'any',
              dataKey: 'device_cpu_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_cpu_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'OBC',
              nodeProcess: 'any',
              dataKey: 'device_cpu_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_cpu_utc_003',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'EPS MB',
              nodeProcess: 'any',
              dataKey: 'device_cpu_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_cpu_utc_001',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'ADCS MCU',
              nodeProcess: 'any',
              dataKey: 'device_cpu_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_cpu_utc_002',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'ADCS Gyro X',
              nodeProcess: 'any',
              dataKey: 'device_imu_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_imu_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'ADCS Gyro Y',
              nodeProcess: 'any',
              dataKey: 'device_imu_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_imu_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'ADCS Gyro Z',
              nodeProcess: 'any',
              dataKey: 'device_imu_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_imu_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-d',
      x: 9,
      y: 0,
      w: 3,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Solar Panel Temperatures',
          displayValues: [
            {
              name: 'Solar Panel Z-',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Solar Panel Z+',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Solar Panel Y-',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Solar Panel Y+',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Solar Pwr Supply X-',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_004',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Solar Pwr Supply X+',
              nodeProcess: 'any',
              dataKey: 'device_breg_temp_005',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_breg_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-e',
      x: 3,
      y: 1,
      w: 3,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'EPS Range Temperatures',
          displayValues: [
            {
              name: 'Motor X',
              nodeProcess: 'any',
              dataKey: 'device_mtr_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_mtr_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Motor Y',
              nodeProcess: 'any',
              dataKey: 'device_mtr_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_mtr_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Motor Z',
              nodeProcess: 'any',
              dataKey: 'device_mtr_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_mtr_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Reaction Wheel',
              nodeProcess: 'any',
              dataKey: 'device_rw_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_rw_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-ee',
      x: 6,
      y: 1,
      w: 3,
      h: 7,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Battery Heaters',
          displayValues: [
            {
              name: 'BATT HEATER 1',
              nodeProcess: 'any',
              dataKey: 'device_htr_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_htr_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'BATT HEATER 2',
              nodeProcess: 'any',
              dataKey: 'device_htr_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_htr_utc_001',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'BATT HEATER 3',
              nodeProcess: 'any',
              dataKey: 'device_htr_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_htr_utc_002',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'BATT HEATER 4',
              nodeProcess: 'any',
              dataKey: 'device_htr_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_htr_utc_003',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-f',
      x: 6,
      y: 2,
      w: 3,
      h: 8,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'EPS Bus Temperatures',
          displayValues: [
            {
              name: 'Bus 000',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 001',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 002',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 003',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 004',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_004',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 005',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_005',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 006',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_006',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Bus 007',
              nodeProcess: 'any',
              dataKey: 'device_bus_temp_007',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_bus_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-g',
      x: 9,
      y: 1,
      w: 3,
      h: 15,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Switch Temperatures',
          displayValues: [
            {
              name: 'Switch 000',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 001',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_001',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 002',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_002',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 003',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_003',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 004',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_004',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 005',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_005',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 006',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_006',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 007',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_007',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 008',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_008',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Switch 009',
              nodeProcess: 'any',
              dataKey: 'device_swch_temp_009',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_swch_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-h',
      x: 3,
      y: 2,
      w: 3,
      h: 8,
      component: {
        name: 'DisplayValue',
        props: {
          name: 'Other Temperatures',
          displayValues: [
            {
              name: 'Sun Sensor',
              nodeProcess: 'any',
              dataKey: 'device_ssen_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_ssen_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Transceiver',
              nodeProcess: 'any',
              dataKey: 'device_tcv_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_tcv_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'GPS',
              nodeProcess: 'any',
              dataKey: 'device_gps_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_gps_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
            {
              name: 'Payload',
              nodeProcess: 'any',
              dataKey: 'device_pload_temp_000',
              dataKeyUpperThreshold: 60,
              timeDataKey: 'device_pload_utc_000',
              unit: 'C',
              processDataKey: (x) => (x - 273.15).toFixed(2),
              processSecondaryDataKey: (x) => `${x.toFixed(2)}K`,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-i',
      x: 0,
      y: 3,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Battery',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'red',
              },
              name: 'Battery MB (C)',
              YDataKey: 'device_batt_temp_000',
              timeDataKey: 'device_batt_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'Batt DB 1 (C)',
              YDataKey: 'device_tsen_temp_000',
              timeDataKey: 'device_tsen_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'Batt DB 2 000 (C)',
              YDataKey: 'device_tsen_temp_001',
              timeDataKey: 'device_tsen_utc_001',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Batt DB 2 001 (C)',
              YDataKey: 'device_tsen_temp_002',
              timeDataKey: 'device_tsen_utc_002',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'brown',
              },
              name: 'Batt DB 2 002 (C)',
              YDataKey: 'device_tsen_temp_003',
              timeDataKey: 'device_tsen_utc_003',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-j',
      x: 6,
      y: 3,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'CPU',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'red',
              },
              name: 'BBB (C)',
              YDataKey: 'device_cpu_temp_000',
              timeDataKey: 'device_cpu_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'OBC (C)',
              YDataKey: 'device_cpu_temp_003',
              timeDataKey: 'device_cpu_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'EPS DU (C)',
              YDataKey: 'device_cpu_temp_001',
              timeDataKey: 'device_cpu_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'CubeComp (C)',
              YDataKey: 'device_cpu_temp_002',
              timeDataKey: 'device_cpu_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'brown',
              },
              name: 'IMU (C)',
              YDataKey: 'device_imu_temp_000',
              timeDataKey: 'device_imu_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-k',
      x: 0,
      y: 4,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'EPS Bus Temperatures',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'red',
              },
              name: 'Bus 000 (C)',
              YDataKey: 'device_bus_temp_000',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'Bus 001 (C)',
              YDataKey: 'device_bus_temp_001',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'Bus 002 (C)',
              YDataKey: 'device_bus_temp_002',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Bus 003 (C)',
              YDataKey: 'device_bus_temp_003',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'brown',
              },
              name: 'Bus 004 (C)',
              YDataKey: 'device_bus_temp_004',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'cyan',
              },
              name: 'Bus 005 (C)',
              YDataKey: 'device_bus_temp_005',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'purple',
              },
              name: 'Bus 006 (C)',
              YDataKey: 'device_bus_temp_006',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'darkseagreen',
              },
              name: 'Bus 007 (C)',
              YDataKey: 'device_bus_temp_007',
              timeDataKey: 'device_bus_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-l',
      x: 6,
      y: 4,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'EPS Solar Panel Tempuratures',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'red',
              },
              name: 'Solar Panel Z- (C)',
              YDataKey: 'device_bcreg_temp_000',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'Solar Panel Z+ (C)',
              YDataKey: 'device_bcreg_temp_001',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'Solar Panel Y- (C)',
              YDataKey: 'device_bcreg_temp_002',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Solar Panel Y+ (C)',
              YDataKey: 'device_breg_temp_003',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'brown',
              },
              name: 'Solar Pwr Supply X- (C)',
              YDataKey: 'device_bcreg_temp_004',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'cyan',
              },
              name: 'Solar Pwr Supply X+ (C)',
              YDataKey: 'device_bcreg_temp_005',
              timeDataKey: 'device_bcreg_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-m',
      x: 0,
      y: 5,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Switch Temperature',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'red',
              },
              name: 'Switch 000 (C)',
              YDataKey: 'device_swch_temp_000',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'Switch 001 (C)',
              YDataKey: 'device_swch_temp_001',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'Switch 002 (C)',
              YDataKey: 'device_swch_temp_002',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Switch 003 (C)',
              YDataKey: 'device_swch_temp_003',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'brown',
              },
              name: 'Switch 004 (C)',
              YDataKey: 'device_swch_temp_004',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'cyan',
              },
              name: 'Switch 005 (C)',
              YDataKey: 'device_swch_temp_005',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'purple',
              },
              name: 'Switch 006 (C)',
              YDataKey: 'device_swch_temp_006',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'darkseagreen',
              },
              name: 'Switch 007 (C)',
              YDataKey: 'device_swch_temp_007',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'pink',
              },
              name: 'Switch 008 (C)',
              YDataKey: 'device_swch_temp_008',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'gray',
              },
              name: 'Switch 009 (C)',
              YDataKey: 'device_swch_temp_009',
              timeDataKey: 'device_swch_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-n',
      x: 6,
      y: 5,
      w: 6,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Switch Temperature',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Motor X (C)',
              YDataKey: 'device_mtr_temp_000',
              timeDataKey: 'device_mtr_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'blue',
              },
              name: 'Motor Y (C)',
              YDataKey: 'device_mtr_temp_001',
              timeDataKey: 'device_mtr_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'orange',
              },
              name: 'Motor Z (C)',
              YDataKey: 'device_mtr_temp_002',
              timeDataKey: 'device_mtr_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Reaction Wheel (C)',
              YDataKey: 'device_rw_temp_000',
              timeDataKey: 'device_rw_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
    {
      i: 'satellite-neutron1-thermal-o',
      x: 0,
      y: 6,
      w: 12,
      h: 18,
      component: {
        name: 'Chart',
        props: {
          name: 'Other Temperatures',
          defaultRange: 'temperature',
          plots: [
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'red',
              },
              name: 'Sun Sensor (C)',
              YDataKey: 'device_ssen_temp_000',
              timeDataKey: 'device_ssen_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'blue',
              },
              name: 'Transceiver (C)',
              YDataKey: 'device_tcv_temp_000',
              timeDataKey: 'device_tcv_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              mode: 'lines+markers',
              marker: {
                color: 'orange',
              },
              name: 'GPS (C)',
              YDataKey: 'device_gps_temp_000',
              timeDataKey: 'device_gps_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
            {
              x: [],
              y: [],
              type: 'scatter',
              marker: {
                color: 'green',
              },
              name: 'Payload (C)',
              YDataKey: 'device_pload_temp_000',
              timeDataKey: 'device_pload_utc_000',
              processYDataKey: (x) => (x - 273.15).toFixed(2),
              nodeProcess: 'any',
              live: true,
            },
          ],
        },
      },
    },
  ],
};
