const testraw = `agent                                   vector<agentstruc>
agent[0]                                agentstruc
agent[0].aprd                           double
agent[0].beat                           beatstruc
agent[0].beat.addr                      char[]
agent[0].beat.bprd                      double
agent[0].beat.bsz                       uint32_t
agent[0].beat.cpu                       float
agent[0].beat.exists                    bool
agent[0].beat.jitter                    double
agent[0].beat.memory                    float
agent[0].beat.node                      string
agent[0].beat.ntype                     NetworkType
agent[0].beat.port                      uint16_t
agent[0].beat.proc                      string
agent[0].beat.user                      char[]
agent[0].beat.utc                       double
agent[0].client                         bool
agent[0].ifcnt                          size_t
agent[0].pid                            int32_t
agent[0].pub                            socket_channel[]
agent[0].pub[0]                         socket_channel
agent[0].pub[0].cudp                    int32_t
agent[0].pub[0].type                    NetworkType
agent[0].pub[1]                         socket_channel
agent[0].pub[1].cudp                    int32_t
agent[0].pub[1].type                    NetworkType
agent[0].pub[2]                         socket_channel
agent[0].pub[2].cudp                    int32_t
agent[0].pub[2].type                    NetworkType
agent[0].pub[3]                         socket_channel
agent[0].pub[3].cudp                    int32_t
agent[0].pub[3].type                    NetworkType
agent[0].pub[4]                         socket_channel
agent[0].pub[4].cudp                    int32_t
agent[0].pub[4].type                    NetworkType
agent[0].pub[5]                         socket_channel
agent[0].pub[5].cudp                    int32_t
agent[0].pub[5].type                    NetworkType
agent[0].pub[6]                         socket_channel
agent[0].pub[6].cudp                    int32_t
agent[0].pub[6].type                    NetworkType
agent[0].pub[7]                         socket_channel
agent[0].pub[7].cudp                    int32_t
agent[0].pub[7].type                    NetworkType
agent[0].pub[8]                         socket_channel
agent[0].pub[8].cudp                    int32_t
agent[0].pub[8].type                    NetworkType
agent[0].pub[9]                         socket_channel
agent[0].pub[9].cudp                    int32_t
agent[0].pub[9].type                    NetworkType
agent[0].req                            socket_channel
agent[0].req.cudp                       int32_t
agent[0].req.type                       NetworkType
agent[0].reqs                           vector<agent_request_entry>
agent[0].server                         bool
agent[0].stateflag                      uint16_t
agent[0].sub                            socket_channel
agent[0].sub.cudp                       int32_t
agent[0].sub.type                       NetworkType
cinfo                                   cosmosstruc
device                                  vector<devicestruc*>
devspec                                 devspecstruc
devspec.ant_cnt                         uint16_t
devspec.batt_cnt                        uint16_t
devspec.bcreg_cnt                       uint16_t
devspec.bus_cnt                         uint16_t
devspec.cam_cnt                         uint16_t
devspec.cpu_cnt                         uint16_t
devspec.disk_cnt                        uint16_t
devspec.gps_cnt                         uint16_t
devspec.htr_cnt                         uint16_t
devspec.imu_cnt                         uint16_t
devspec.mcc_cnt                         uint16_t
devspec.motr_cnt                        uint16_t
devspec.mtr_cnt                         uint16_t
devspec.pload_cnt                       uint16_t
devspec.prop_cnt                        uint16_t
devspec.psen_cnt                        uint16_t
devspec.pvstrg_cnt                      uint16_t
devspec.rot_cnt                         uint16_t
devspec.rw_cnt                          uint16_t
devspec.rxr_cnt                         uint16_t
devspec.ssen_cnt                        uint16_t
devspec.stt_cnt                         uint16_t
devspec.suchi_cnt                       uint16_t
devspec.swch_cnt                        uint16_t
devspec.tcu_cnt                         uint16_t
devspec.tcv_cnt                         uint16_t
devspec.telem_cnt                       uint16_t
devspec.thst_cnt                        uint16_t
devspec.tnc_cnt                         uint16_t
devspec.tsen_cnt                        uint16_t
devspec.txr_cnt                         uint16_t
equation                                vector<equationstruc>
event                                   vector<eventstruc>
event[0]                                eventstruc
event[0].cbytes                         float
event[0].cenergy                        float
event[0].cmass                          float
event[0].condition                      string
event[0].ctime                          double
event[0].data                           string
event[0].dbytes                         float
event[0].denergy                        float
event[0].dmass                          float
event[0].dtime                          double
event[0].flag                           uint32_t
event[0].handle                         jsonhandle
event[0].handle.hash                    uint16_t
event[0].handle.index                   uint16_t
event[0].name                           string
event[0].node                           string
event[0].type                           uint32_t
event[0].user                           string
event[0].utc                            double
event[0].utcexec                        double
event[0].value                          double
faces                                   vector<facestruc>
jmapped                                 uint16_t
json                                    jsonnode
json.devgen                             string
json.devspec                            string
json.faces                              string
json.name                               string
json.node                               string
json.pieces                             string
json.ports                              string
json.state                              string
json.targets                            string
json.utcstart                           string
json.vertexs                            string
node                                    nodestruc
node.agent                              string
node.agent_cnt                          uint16_t
node.azfrom                             float
node.azto                               float
node.device_cnt                         uint16_t
node.downtime                           uint32_t
node.elfrom                             float
node.elto                               float
node.event_cnt                          uint16_t
node.face_cnt                           uint16_t
node.flags                              uint16_t
node.lastevent                          string
node.lasteventutc                       double
node.loc                                locstruc
node.loc.att                            attstruc
node.loc.att.extra                      extraatt
node.loc.att.extra.b2j                  rmatrix
node.loc.att.extra.b2j.row              rvector[]
node.loc.att.extra.b2j.row[0]           rvector
node.loc.att.extra.b2j.row[0].col       double[]
node.loc.att.extra.b2j.row[0].col[0]    double
node.loc.att.extra.b2j.row[0].col[1]    double
node.loc.att.extra.b2j.row[0].col[2]    double
node.loc.att.extra.b2j.row[1]           rvector
node.loc.att.extra.b2j.row[1].col       double[]
node.loc.att.extra.b2j.row[1].col[0]    double
node.loc.att.extra.b2j.row[1].col[1]    double
node.loc.att.extra.b2j.row[1].col[2]    double
node.loc.att.extra.b2j.row[2]           rvector
node.loc.att.extra.b2j.row[2].col       double[]
node.loc.att.extra.b2j.row[2].col[0]    double
node.loc.att.extra.b2j.row[2].col[1]    double
node.loc.att.extra.b2j.row[2].col[2]    double
node.loc.att.extra.j2b                  rmatrix
node.loc.att.extra.j2b.row              rvector[]
node.loc.att.extra.j2b.row[0]           rvector
node.loc.att.extra.j2b.row[0].col       double[]
node.loc.att.extra.j2b.row[0].col[0]    double
node.loc.att.extra.j2b.row[0].col[1]    double
node.loc.att.extra.j2b.row[0].col[2]    double
node.loc.att.extra.j2b.row[1]           rvector
node.loc.att.extra.j2b.row[1].col       double[]
node.loc.att.extra.j2b.row[1].col[0]    double
node.loc.att.extra.j2b.row[1].col[1]    double
node.loc.att.extra.j2b.row[1].col[2]    double
node.loc.att.extra.j2b.row[2]           rvector
node.loc.att.extra.j2b.row[2].col       double[]
node.loc.att.extra.j2b.row[2].col[0]    double
node.loc.att.extra.j2b.row[2].col[1]    double
node.loc.att.extra.j2b.row[2].col[2]    double
node.loc.att.extra.utc                  double
node.loc.att.geoc                       qatt
node.loc.att.geoc.a                     rvector
node.loc.att.geoc.a.col                 double[]
node.loc.att.geoc.a.col[0]              double
node.loc.att.geoc.a.col[1]              double
node.loc.att.geoc.a.col[2]              double
node.loc.att.geoc.pass                  uint32_t
node.loc.att.geoc.s                     quaternion
node.loc.att.geoc.s.d                   cvector
node.loc.att.geoc.s.d.x                 double
node.loc.att.geoc.s.d.y                 double
node.loc.att.geoc.s.d.z                 double
node.loc.att.geoc.s.w                   double
node.loc.att.geoc.utc                   double
node.loc.att.geoc.v                     rvector
node.loc.att.geoc.v.col                 double[]
node.loc.att.geoc.v.col[0]              double
node.loc.att.geoc.v.col[1]              double
node.loc.att.geoc.v.col[2]              double
node.loc.att.icrf                       qatt
node.loc.att.icrf.a                     rvector
node.loc.att.icrf.a.col                 double[]
node.loc.att.icrf.a.col[0]              double
node.loc.att.icrf.a.col[1]              double
node.loc.att.icrf.a.col[2]              double
node.loc.att.icrf.pass                  uint32_t
node.loc.att.icrf.s                     quaternion
node.loc.att.icrf.s.d                   cvector
node.loc.att.icrf.s.d.x                 double
node.loc.att.icrf.s.d.y                 double
node.loc.att.icrf.s.d.z                 double
node.loc.att.icrf.s.w                   double
node.loc.att.icrf.utc                   double
node.loc.att.icrf.v                     rvector
node.loc.att.icrf.v.col                 double[]
node.loc.att.icrf.v.col[0]              double
node.loc.att.icrf.v.col[1]              double
node.loc.att.icrf.v.col[2]              double
node.loc.att.lvlh                       qatt
node.loc.att.lvlh.a                     rvector
node.loc.att.lvlh.a.col                 double[]
node.loc.att.lvlh.a.col[0]              double
node.loc.att.lvlh.a.col[1]              double
node.loc.att.lvlh.a.col[2]              double
node.loc.att.lvlh.pass                  uint32_t
node.loc.att.lvlh.s                     quaternion
node.loc.att.lvlh.s.d                   cvector
node.loc.att.lvlh.s.d.x                 double
node.loc.att.lvlh.s.d.y                 double
node.loc.att.lvlh.s.d.z                 double
node.loc.att.lvlh.s.w                   double
node.loc.att.lvlh.utc                   double
node.loc.att.lvlh.v                     rvector
node.loc.att.lvlh.v.col                 double[]
node.loc.att.lvlh.v.col[0]              double
node.loc.att.lvlh.v.col[1]              double
node.loc.att.lvlh.v.col[2]              double
node.loc.att.selc                       qatt
node.loc.att.selc.a                     rvector
node.loc.att.selc.a.col                 double[]
node.loc.att.selc.a.col[0]              double
node.loc.att.selc.a.col[1]              double
node.loc.att.selc.a.col[2]              double
node.loc.att.selc.pass                  uint32_t
node.loc.att.selc.s                     quaternion
node.loc.att.selc.s.d                   cvector
node.loc.att.selc.s.d.x                 double
node.loc.att.selc.s.d.y                 double
node.loc.att.selc.s.d.z                 double
node.loc.att.selc.s.w                   double
node.loc.att.selc.utc                   double
node.loc.att.selc.v                     rvector
node.loc.att.selc.v.col                 double[]
node.loc.att.selc.v.col[0]              double
node.loc.att.selc.v.col[1]              double
node.loc.att.selc.v.col[2]              double
node.loc.att.topo                       qatt
node.loc.att.topo.a                     rvector
node.loc.att.topo.a.col                 double[]
node.loc.att.topo.a.col[0]              double
node.loc.att.topo.a.col[1]              double
node.loc.att.topo.a.col[2]              double
node.loc.att.topo.pass                  uint32_t
node.loc.att.topo.s                     quaternion
node.loc.att.topo.s.d                   cvector
node.loc.att.topo.s.d.x                 double
node.loc.att.topo.s.d.y                 double
node.loc.att.topo.s.d.z                 double
node.loc.att.topo.s.w                   double
node.loc.att.topo.utc                   double
node.loc.att.topo.v                     rvector
node.loc.att.topo.v.col                 double[]
node.loc.att.topo.v.col[0]              double
node.loc.att.topo.v.col[1]              double
node.loc.att.topo.v.col[2]              double
node.loc.att.utc                        double
node.loc.pos                            posstruc
node.loc.pos.bearth                     rvector
node.loc.pos.bearth.col                 double[]
node.loc.pos.bearth.col[0]              double
node.loc.pos.bearth.col[1]              double
node.loc.pos.bearth.col[2]              double
node.loc.pos.earthsep                   float
node.loc.pos.eci                        cartpos
node.loc.pos.eci.a                      rvector
node.loc.pos.eci.a.col                  double[]
node.loc.pos.eci.a.col[0]               double
node.loc.pos.eci.a.col[1]               double
node.loc.pos.eci.a.col[2]               double
node.loc.pos.eci.pass                   uint32_t
node.loc.pos.eci.s                      rvector
node.loc.pos.eci.s.col                  double[]
node.loc.pos.eci.s.col[0]               double
node.loc.pos.eci.s.col[1]               double
node.loc.pos.eci.s.col[2]               double
node.loc.pos.eci.utc                    double
node.loc.pos.eci.v                      rvector
node.loc.pos.eci.v.col                  double[]
node.loc.pos.eci.v.col[0]               double
node.loc.pos.eci.v.col[1]               double
node.loc.pos.eci.v.col[2]               double
node.loc.pos.extra                      extrapos
node.loc.pos.extra.closest              uint16_t
node.loc.pos.extra.dde2j                rmatrix
node.loc.pos.extra.dde2j.row            rvector[]
node.loc.pos.extra.dde2j.row[0]         rvector
node.loc.pos.extra.dde2j.row[0].col     double[]
node.loc.pos.extra.dde2j.row[0].col[0]  double
node.loc.pos.extra.dde2j.row[0].col[1]  double
node.loc.pos.extra.dde2j.row[0].col[2]  double
node.loc.pos.extra.dde2j.row[1]         rvector
node.loc.pos.extra.dde2j.row[1].col     double[]
node.loc.pos.extra.dde2j.row[1].col[0]  double
node.loc.pos.extra.dde2j.row[1].col[1]  double
node.loc.pos.extra.dde2j.row[1].col[2]  double
node.loc.pos.extra.dde2j.row[2]         rvector
node.loc.pos.extra.dde2j.row[2].col     double[]
node.loc.pos.extra.dde2j.row[2].col[0]  double
node.loc.pos.extra.dde2j.row[2].col[1]  double
node.loc.pos.extra.dde2j.row[2].col[2]  double
node.loc.pos.extra.ddj2e                rmatrix
node.loc.pos.extra.ddj2e.row            rvector[]
node.loc.pos.extra.ddj2e.row[0]         rvector
node.loc.pos.extra.ddj2e.row[0].col     double[]
node.loc.pos.extra.ddj2e.row[0].col[0]  double
node.loc.pos.extra.ddj2e.row[0].col[1]  double
node.loc.pos.extra.ddj2e.row[0].col[2]  double
node.loc.pos.extra.ddj2e.row[1]         rvector
node.loc.pos.extra.ddj2e.row[1].col     double[]
node.loc.pos.extra.ddj2e.row[1].col[0]  double
node.loc.pos.extra.ddj2e.row[1].col[1]  double
node.loc.pos.extra.ddj2e.row[1].col[2]  double
node.loc.pos.extra.ddj2e.row[2]         rvector
node.loc.pos.extra.ddj2e.row[2].col     double[]
node.loc.pos.extra.ddj2e.row[2].col[0]  double
node.loc.pos.extra.ddj2e.row[2].col[1]  double
node.loc.pos.extra.ddj2e.row[2].col[2]  double
node.loc.pos.extra.de2j                 rmatrix
node.loc.pos.extra.de2j.row             rvector[]
node.loc.pos.extra.de2j.row[0]          rvector
node.loc.pos.extra.de2j.row[0].col      double[]
node.loc.pos.extra.de2j.row[0].col[0]   double
node.loc.pos.extra.de2j.row[0].col[1]   double
node.loc.pos.extra.de2j.row[0].col[2]   double
node.loc.pos.extra.de2j.row[1]          rvector
node.loc.pos.extra.de2j.row[1].col      double[]
node.loc.pos.extra.de2j.row[1].col[0]   double
node.loc.pos.extra.de2j.row[1].col[1]   double
node.loc.pos.extra.de2j.row[1].col[2]   double
node.loc.pos.extra.de2j.row[2]          rvector
node.loc.pos.extra.de2j.row[2].col      double[]
node.loc.pos.extra.de2j.row[2].col[0]   double
node.loc.pos.extra.de2j.row[2].col[1]   double
node.loc.pos.extra.de2j.row[2].col[2]   double
node.loc.pos.extra.dj2e                 rmatrix
node.loc.pos.extra.dj2e.row             rvector[]
node.loc.pos.extra.dj2e.row[0]          rvector
node.loc.pos.extra.dj2e.row[0].col      double[]
node.loc.pos.extra.dj2e.row[0].col[0]   double
node.loc.pos.extra.dj2e.row[0].col[1]   double
node.loc.pos.extra.dj2e.row[0].col[2]   double
node.loc.pos.extra.dj2e.row[1]          rvector
node.loc.pos.extra.dj2e.row[1].col      double[]
node.loc.pos.extra.dj2e.row[1].col[0]   double
node.loc.pos.extra.dj2e.row[1].col[1]   double
node.loc.pos.extra.dj2e.row[1].col[2]   double
node.loc.pos.extra.dj2e.row[2]          rvector
node.loc.pos.extra.dj2e.row[2].col      double[]
node.loc.pos.extra.dj2e.row[2].col[0]   double
node.loc.pos.extra.dj2e.row[2].col[1]   double
node.loc.pos.extra.dj2e.row[2].col[2]   double
node.loc.pos.extra.ds2t                 rmatrix
node.loc.pos.extra.ds2t.row             rvector[]
node.loc.pos.extra.ds2t.row[0]          rvector
node.loc.pos.extra.ds2t.row[0].col      double[]
node.loc.pos.extra.ds2t.row[0].col[0]   double
node.loc.pos.extra.ds2t.row[0].col[1]   double
node.loc.pos.extra.ds2t.row[0].col[2]   double
node.loc.pos.extra.ds2t.row[1]          rvector
node.loc.pos.extra.ds2t.row[1].col      double[]
node.loc.pos.extra.ds2t.row[1].col[0]   double
node.loc.pos.extra.ds2t.row[1].col[1]   double
node.loc.pos.extra.ds2t.row[1].col[2]   double
node.loc.pos.extra.ds2t.row[2]          rvector
node.loc.pos.extra.ds2t.row[2].col      double[]
node.loc.pos.extra.ds2t.row[2].col[0]   double
node.loc.pos.extra.ds2t.row[2].col[1]   double
node.loc.pos.extra.ds2t.row[2].col[2]   double
node.loc.pos.extra.dt2s                 rmatrix
node.loc.pos.extra.dt2s.row             rvector[]
node.loc.pos.extra.dt2s.row[0]          rvector
node.loc.pos.extra.dt2s.row[0].col      double[]
node.loc.pos.extra.dt2s.row[0].col[0]   double
node.loc.pos.extra.dt2s.row[0].col[1]   double
node.loc.pos.extra.dt2s.row[0].col[2]   double
node.loc.pos.extra.dt2s.row[1]          rvector
node.loc.pos.extra.dt2s.row[1].col      double[]
node.loc.pos.extra.dt2s.row[1].col[0]   double
node.loc.pos.extra.dt2s.row[1].col[1]   double
node.loc.pos.extra.dt2s.row[1].col[2]   double
node.loc.pos.extra.dt2s.row[2]          rvector
node.loc.pos.extra.dt2s.row[2].col      double[]
node.loc.pos.extra.dt2s.row[2].col[0]   double
node.loc.pos.extra.dt2s.row[2].col[1]   double
node.loc.pos.extra.dt2s.row[2].col[2]   double
node.loc.pos.extra.e2j                  rmatrix
node.loc.pos.extra.e2j.row              rvector[]
node.loc.pos.extra.e2j.row[0]           rvector
node.loc.pos.extra.e2j.row[0].col       double[]
node.loc.pos.extra.e2j.row[0].col[0]    double
node.loc.pos.extra.e2j.row[0].col[1]    double
node.loc.pos.extra.e2j.row[0].col[2]    double
node.loc.pos.extra.e2j.row[1]           rvector
node.loc.pos.extra.e2j.row[1].col       double[]
node.loc.pos.extra.e2j.row[1].col[0]    double
node.loc.pos.extra.e2j.row[1].col[1]    double
node.loc.pos.extra.e2j.row[1].col[2]    double
node.loc.pos.extra.e2j.row[2]           rvector
node.loc.pos.extra.e2j.row[2].col       double[]
node.loc.pos.extra.e2j.row[2].col[0]    double
node.loc.pos.extra.e2j.row[2].col[1]    double
node.loc.pos.extra.e2j.row[2].col[2]    double
node.loc.pos.extra.j2e                  rmatrix
node.loc.pos.extra.j2e.row              rvector[]
node.loc.pos.extra.j2e.row[0]           rvector
node.loc.pos.extra.j2e.row[0].col       double[]
node.loc.pos.extra.j2e.row[0].col[0]    double
node.loc.pos.extra.j2e.row[0].col[1]    double
node.loc.pos.extra.j2e.row[0].col[2]    double
node.loc.pos.extra.j2e.row[1]           rvector
node.loc.pos.extra.j2e.row[1].col       double[]
node.loc.pos.extra.j2e.row[1].col[0]    double
node.loc.pos.extra.j2e.row[1].col[1]    double
node.loc.pos.extra.j2e.row[1].col[2]    double
node.loc.pos.extra.j2e.row[2]           rvector
node.loc.pos.extra.j2e.row[2].col       double[]
node.loc.pos.extra.j2e.row[2].col[0]    double
node.loc.pos.extra.j2e.row[2].col[1]    double
node.loc.pos.extra.j2e.row[2].col[2]    double
node.loc.pos.extra.j2s                  rmatrix
node.loc.pos.extra.j2s.row              rvector[]
node.loc.pos.extra.j2s.row[0]           rvector
node.loc.pos.extra.j2s.row[0].col       double[]
node.loc.pos.extra.j2s.row[0].col[0]    double
node.loc.pos.extra.j2s.row[0].col[1]    double
node.loc.pos.extra.j2s.row[0].col[2]    double
node.loc.pos.extra.j2s.row[1]           rvector
node.loc.pos.extra.j2s.row[1].col       double[]
node.loc.pos.extra.j2s.row[1].col[0]    double
node.loc.pos.extra.j2s.row[1].col[1]    double
node.loc.pos.extra.j2s.row[1].col[2]    double
node.loc.pos.extra.j2s.row[2]           rvector
node.loc.pos.extra.j2s.row[2].col       double[]
node.loc.pos.extra.j2s.row[2].col[0]    double
node.loc.pos.extra.j2s.row[2].col[1]    double
node.loc.pos.extra.j2s.row[2].col[2]    double
node.loc.pos.extra.j2t                  rmatrix
node.loc.pos.extra.j2t.row              rvector[]
node.loc.pos.extra.j2t.row[0]           rvector
node.loc.pos.extra.j2t.row[0].col       double[]
node.loc.pos.extra.j2t.row[0].col[0]    double
node.loc.pos.extra.j2t.row[0].col[1]    double
node.loc.pos.extra.j2t.row[0].col[2]    double
node.loc.pos.extra.j2t.row[1]           rvector
node.loc.pos.extra.j2t.row[1].col       double[]
node.loc.pos.extra.j2t.row[1].col[0]    double
node.loc.pos.extra.j2t.row[1].col[1]    double
node.loc.pos.extra.j2t.row[1].col[2]    double
node.loc.pos.extra.j2t.row[2]           rvector
node.loc.pos.extra.j2t.row[2].col       double[]
node.loc.pos.extra.j2t.row[2].col[0]    double
node.loc.pos.extra.j2t.row[2].col[1]    double
node.loc.pos.extra.j2t.row[2].col[2]    double
node.loc.pos.extra.s2j                  rmatrix
node.loc.pos.extra.s2j.row              rvector[]
node.loc.pos.extra.s2j.row[0]           rvector
node.loc.pos.extra.s2j.row[0].col       double[]
node.loc.pos.extra.s2j.row[0].col[0]    double
node.loc.pos.extra.s2j.row[0].col[1]    double
node.loc.pos.extra.s2j.row[0].col[2]    double
node.loc.pos.extra.s2j.row[1]           rvector
node.loc.pos.extra.s2j.row[1].col       double[]
node.loc.pos.extra.s2j.row[1].col[0]    double
node.loc.pos.extra.s2j.row[1].col[1]    double
node.loc.pos.extra.s2j.row[1].col[2]    double
node.loc.pos.extra.s2j.row[2]           rvector
node.loc.pos.extra.s2j.row[2].col       double[]
node.loc.pos.extra.s2j.row[2].col[0]    double
node.loc.pos.extra.s2j.row[2].col[1]    double
node.loc.pos.extra.s2j.row[2].col[2]    double
node.loc.pos.extra.s2t                  rmatrix
node.loc.pos.extra.s2t.row              rvector[]
node.loc.pos.extra.s2t.row[0]           rvector
node.loc.pos.extra.s2t.row[0].col       double[]
node.loc.pos.extra.s2t.row[0].col[0]    double
node.loc.pos.extra.s2t.row[0].col[1]    double
node.loc.pos.extra.s2t.row[0].col[2]    double
node.loc.pos.extra.s2t.row[1]           rvector
node.loc.pos.extra.s2t.row[1].col       double[]
node.loc.pos.extra.s2t.row[1].col[0]    double
node.loc.pos.extra.s2t.row[1].col[1]    double
node.loc.pos.extra.s2t.row[1].col[2]    double
node.loc.pos.extra.s2t.row[2]           rvector
node.loc.pos.extra.s2t.row[2].col       double[]
node.loc.pos.extra.s2t.row[2].col[0]    double
node.loc.pos.extra.s2t.row[2].col[1]    double
node.loc.pos.extra.s2t.row[2].col[2]    double
node.loc.pos.extra.sun2earth            cartpos
node.loc.pos.extra.sun2earth.a          rvector
node.loc.pos.extra.sun2earth.a.col      double[]
node.loc.pos.extra.sun2earth.a.col[0]   double
node.loc.pos.extra.sun2earth.a.col[1]   double
node.loc.pos.extra.sun2earth.a.col[2]   double
node.loc.pos.extra.sun2earth.pass       uint32_t
node.loc.pos.extra.sun2earth.s          rvector
node.loc.pos.extra.sun2earth.s.col      double[]
node.loc.pos.extra.sun2earth.s.col[0]   double
node.loc.pos.extra.sun2earth.s.col[1]   double
node.loc.pos.extra.sun2earth.s.col[2]   double
node.loc.pos.extra.sun2earth.utc        double
node.loc.pos.extra.sun2earth.v          rvector
node.loc.pos.extra.sun2earth.v.col      double[]
node.loc.pos.extra.sun2earth.v.col[0]   double
node.loc.pos.extra.sun2earth.v.col[1]   double
node.loc.pos.extra.sun2earth.v.col[2]   double
node.loc.pos.extra.sun2moon             cartpos
node.loc.pos.extra.sun2moon.a           rvector
node.loc.pos.extra.sun2moon.a.col       double[]
node.loc.pos.extra.sun2moon.a.col[0]    double
node.loc.pos.extra.sun2moon.a.col[1]    double
node.loc.pos.extra.sun2moon.a.col[2]    double
node.loc.pos.extra.sun2moon.pass        uint32_t
node.loc.pos.extra.sun2moon.s           rvector
node.loc.pos.extra.sun2moon.s.col       double[]
node.loc.pos.extra.sun2moon.s.col[0]    double
node.loc.pos.extra.sun2moon.s.col[1]    double
node.loc.pos.extra.sun2moon.s.col[2]    double
node.loc.pos.extra.sun2moon.utc         double
node.loc.pos.extra.sun2moon.v           rvector
node.loc.pos.extra.sun2moon.v.col       double[]
node.loc.pos.extra.sun2moon.v.col[0]    double
node.loc.pos.extra.sun2moon.v.col[1]    double
node.loc.pos.extra.sun2moon.v.col[2]    double
node.loc.pos.extra.t2j                  rmatrix
node.loc.pos.extra.t2j.row              rvector[]
node.loc.pos.extra.t2j.row[0]           rvector
node.loc.pos.extra.t2j.row[0].col       double[]
node.loc.pos.extra.t2j.row[0].col[0]    double
node.loc.pos.extra.t2j.row[0].col[1]    double
node.loc.pos.extra.t2j.row[0].col[2]    double
node.loc.pos.extra.t2j.row[1]           rvector
node.loc.pos.extra.t2j.row[1].col       double[]
node.loc.pos.extra.t2j.row[1].col[0]    double
node.loc.pos.extra.t2j.row[1].col[1]    double
node.loc.pos.extra.t2j.row[1].col[2]    double
node.loc.pos.extra.t2j.row[2]           rvector
node.loc.pos.extra.t2j.row[2].col       double[]
node.loc.pos.extra.t2j.row[2].col[0]    double
node.loc.pos.extra.t2j.row[2].col[1]    double
node.loc.pos.extra.t2j.row[2].col[2]    double
node.loc.pos.extra.t2s                  rmatrix
node.loc.pos.extra.t2s.row              rvector[]
node.loc.pos.extra.t2s.row[0]           rvector
node.loc.pos.extra.t2s.row[0].col       double[]
node.loc.pos.extra.t2s.row[0].col[0]    double
node.loc.pos.extra.t2s.row[0].col[1]    double
node.loc.pos.extra.t2s.row[0].col[2]    double
node.loc.pos.extra.t2s.row[1]           rvector
node.loc.pos.extra.t2s.row[1].col       double[]
node.loc.pos.extra.t2s.row[1].col[0]    double
node.loc.pos.extra.t2s.row[1].col[1]    double
node.loc.pos.extra.t2s.row[1].col[2]    double
node.loc.pos.extra.t2s.row[2]           rvector
node.loc.pos.extra.t2s.row[2].col       double[]
node.loc.pos.extra.t2s.row[2].col[0]    double
node.loc.pos.extra.t2s.row[2].col[1]    double
node.loc.pos.extra.t2s.row[2].col[2]    double
node.loc.pos.extra.tdb                  double
node.loc.pos.extra.tt                   double
node.loc.pos.extra.ut                   double
node.loc.pos.extra.utc                  double
node.loc.pos.geoc                       cartpos
node.loc.pos.geoc.a                     rvector
node.loc.pos.geoc.a.col                 double[]
node.loc.pos.geoc.a.col[0]              double
node.loc.pos.geoc.a.col[1]              double
node.loc.pos.geoc.a.col[2]              double
node.loc.pos.geoc.pass                  uint32_t
node.loc.pos.geoc.s                     rvector
node.loc.pos.geoc.s.col                 double[]
node.loc.pos.geoc.s.col[0]              double
node.loc.pos.geoc.s.col[1]              double
node.loc.pos.geoc.s.col[2]              double
node.loc.pos.geoc.utc                   double
node.loc.pos.geoc.v                     rvector
node.loc.pos.geoc.v.col                 double[]
node.loc.pos.geoc.v.col[0]              double
node.loc.pos.geoc.v.col[1]              double
node.loc.pos.geoc.v.col[2]              double
node.loc.pos.geod                       geoidpos
node.loc.pos.geod.a                     gvector
node.loc.pos.geod.a.h                   double
node.loc.pos.geod.a.lat                 double
node.loc.pos.geod.a.lon                 double
node.loc.pos.geod.pass                  uint32_t
node.loc.pos.geod.s                     gvector
node.loc.pos.geod.s.h                   double
node.loc.pos.geod.s.lat                 double
node.loc.pos.geod.s.lon                 double
node.loc.pos.geod.utc                   double
node.loc.pos.geod.v                     gvector
node.loc.pos.geod.v.h                   double
node.loc.pos.geod.v.lat                 double
node.loc.pos.geod.v.lon                 double
node.loc.pos.geos                       spherpos
node.loc.pos.geos.a                     svector
node.loc.pos.geos.a.lambda              double
node.loc.pos.geos.a.phi                 double
node.loc.pos.geos.a.r                   double
node.loc.pos.geos.pass                  uint32_t
node.loc.pos.geos.s                     svector
node.loc.pos.geos.s.lambda              double
node.loc.pos.geos.s.phi                 double
node.loc.pos.geos.s.r                   double
node.loc.pos.geos.utc                   double
node.loc.pos.geos.v                     svector
node.loc.pos.geos.v.lambda              double
node.loc.pos.geos.v.phi                 double
node.loc.pos.geos.v.r                   double
node.loc.pos.icrf                       cartpos
node.loc.pos.icrf.a                     rvector
node.loc.pos.icrf.a.col                 double[]
node.loc.pos.icrf.a.col[0]              double
node.loc.pos.icrf.a.col[1]              double
node.loc.pos.icrf.a.col[2]              double
node.loc.pos.icrf.pass                  uint32_t
node.loc.pos.icrf.s                     rvector
node.loc.pos.icrf.s.col                 double[]
node.loc.pos.icrf.s.col[0]              double
node.loc.pos.icrf.s.col[1]              double
node.loc.pos.icrf.s.col[2]              double
node.loc.pos.icrf.utc                   double
node.loc.pos.icrf.v                     rvector
node.loc.pos.icrf.v.col                 double[]
node.loc.pos.icrf.v.col[0]              double
node.loc.pos.icrf.v.col[1]              double
node.loc.pos.icrf.v.col[2]              double
node.loc.pos.moonsep                    float
node.loc.pos.orbit                      double
node.loc.pos.sci                        cartpos
node.loc.pos.sci.a                      rvector
node.loc.pos.sci.a.col                  double[]
node.loc.pos.sci.a.col[0]               double
node.loc.pos.sci.a.col[1]               double
node.loc.pos.sci.a.col[2]               double
node.loc.pos.sci.pass                   uint32_t
node.loc.pos.sci.s                      rvector
node.loc.pos.sci.s.col                  double[]
node.loc.pos.sci.s.col[0]               double
node.loc.pos.sci.s.col[1]               double
node.loc.pos.sci.s.col[2]               double
node.loc.pos.sci.utc                    double
node.loc.pos.sci.v                      rvector
node.loc.pos.sci.v.col                  double[]
node.loc.pos.sci.v.col[0]               double
node.loc.pos.sci.v.col[1]               double
node.loc.pos.sci.v.col[2]               double
node.loc.pos.selc                       cartpos
node.loc.pos.selc.a                     rvector
node.loc.pos.selc.a.col                 double[]
node.loc.pos.selc.a.col[0]              double
node.loc.pos.selc.a.col[1]              double
node.loc.pos.selc.a.col[2]              double
node.loc.pos.selc.pass                  uint32_t
node.loc.pos.selc.s                     rvector
node.loc.pos.selc.s.col                 double[]
node.loc.pos.selc.s.col[0]              double
node.loc.pos.selc.s.col[1]              double
node.loc.pos.selc.s.col[2]              double
node.loc.pos.selc.utc                   double
node.loc.pos.selc.v                     rvector
node.loc.pos.selc.v.col                 double[]
node.loc.pos.selc.v.col[0]              double
node.loc.pos.selc.v.col[1]              double
node.loc.pos.selc.v.col[2]              double
node.loc.pos.selg                       geoidpos
node.loc.pos.selg.a                     gvector
node.loc.pos.selg.a.h                   double
node.loc.pos.selg.a.lat                 double
node.loc.pos.selg.a.lon                 double
node.loc.pos.selg.pass                  uint32_t
node.loc.pos.selg.s                     gvector
node.loc.pos.selg.s.h                   double
node.loc.pos.selg.s.lat                 double
node.loc.pos.selg.s.lon                 double
node.loc.pos.selg.utc                   double
node.loc.pos.selg.v                     gvector
node.loc.pos.selg.v.h                   double
node.loc.pos.selg.v.lat                 double
node.loc.pos.selg.v.lon                 double
node.loc.pos.sunradiance                float
node.loc.pos.sunsize                    float
node.loc.pos.utc                        double
node.loc.utc                            double
node.name                               string
node.normal_cnt                         uint16_t
node.phys                               physicsstruc
node.phys.adrag                         Vector
node.phys.adrag.w                       double
node.phys.adrag.x                       double
node.phys.adrag.y                       double
node.phys.adrag.z                       double
node.phys.area                          float
node.phys.atorque                       Vector
node.phys.atorque.w                     double
node.phys.atorque.x                     double
node.phys.atorque.y                     double
node.phys.atorque.z                     double
node.phys.battcap                       float
node.phys.battlev                       float
node.phys.com                           Vector
node.phys.com.w                         double
node.phys.com.x                         double
node.phys.com.y                         double
node.phys.com.z                         double
node.phys.ctorque                       Vector
node.phys.ctorque.w                     double
node.phys.ctorque.x                     double
node.phys.ctorque.y                     double
node.phys.ctorque.z                     double
node.phys.dt                            double
node.phys.dtj                           double
node.phys.fdrag                         Vector
node.phys.fdrag.w                       double
node.phys.fdrag.x                       double
node.phys.fdrag.y                       double
node.phys.fdrag.z                       double
node.phys.ftorque                       Vector
node.phys.ftorque.w                     double
node.phys.ftorque.x                     double
node.phys.ftorque.y                     double
node.phys.ftorque.z                     double
node.phys.gtorque                       Vector
node.phys.gtorque.w                     double
node.phys.gtorque.x                     double
node.phys.gtorque.y                     double
node.phys.gtorque.z                     double
node.phys.hcap                          float
node.phys.heat                          float
node.phys.hmomentum                     Vector
node.phys.hmomentum.w                   double
node.phys.hmomentum.x                   double
node.phys.hmomentum.y                   double
node.phys.hmomentum.z                   double
node.phys.htorque                       Vector
node.phys.htorque.w                     double
node.phys.htorque.x                     double
node.phys.htorque.y                     double
node.phys.htorque.z                     double
node.phys.mass                          float
node.phys.mjdaccel                      double
node.phys.mjddiff                       double
node.phys.mode                          int32_t
node.phys.moi                           Vector
node.phys.moi.w                         double
node.phys.moi.x                         double
node.phys.moi.y                         double
node.phys.moi.z                         double
node.phys.powgen                        float
node.phys.powuse                        float
node.phys.rdrag                         Vector
node.phys.rdrag.w                       double
node.phys.rdrag.x                       double
node.phys.rdrag.y                       double
node.phys.rdrag.z                       double
node.phys.rtorque                       Vector
node.phys.rtorque.w                     double
node.phys.rtorque.x                     double
node.phys.rtorque.y                     double
node.phys.rtorque.z                     double
node.phys.temp                          float
node.phys.thrust                        Vector
node.phys.thrust.w                      double
node.phys.thrust.x                      double
node.phys.thrust.y                      double
node.phys.thrust.z                      double
node.phys.triangles                     vector<trianglestruc>
node.phys.utc                           double
node.phys.vertices                      vector<Vector>
node.piece_cnt                          uint16_t
node.port_cnt                           uint16_t
node.powmode                            int16_t
node.range                              float
node.state                              uint16_t
node.target_cnt                         uint16_t
node.tle_cnt                            uint16_t
node.type                               uint16_t
node.user_cnt                           uint16_t
node.utc                                double
node.utcoffset                          double
node.utcstart                           double
node.vertex_cnt                         uint16_t
normals                                 vector<vertexstruc>
obj                                     wavefront
obj.Faces                               vector<face>
obj.Groups                              vector<group>
obj.Groups[0]                           group
obj.Groups[0].com                       Vector
obj.Groups[0].com.w                     double
obj.Groups[0].com.x                     double
obj.Groups[0].com.y                     double
obj.Groups[0].com.z                     double
obj.Groups[0].faceidx                   vector<size_t>
obj.Groups[0].lineidx                   vector<size_t>
obj.Groups[0].materialidx               size_t
obj.Groups[0].name                      string
obj.Groups[0].pointidx                  vector<size_t>
obj.Groups[0].volume                    double
obj.Lines                               vector<line>
obj.Materials                           vector<material>
obj.Materials[0]                        material
obj.Materials[0].ambient                Vector
obj.Materials[0].ambient.w              double
obj.Materials[0].ambient.x              double
obj.Materials[0].ambient.y              double
obj.Materials[0].ambient.z              double
obj.Materials[0].density                float
obj.Materials[0].diffuse                Vector
obj.Materials[0].diffuse.w              double
obj.Materials[0].diffuse.x              double
obj.Materials[0].diffuse.y              double
obj.Materials[0].diffuse.z              double
obj.Materials[0].name                   string
obj.Materials[0].specular               Vector
obj.Materials[0].specular.w             double
obj.Materials[0].specular.x             double
obj.Materials[0].specular.y             double
obj.Materials[0].specular.z             double
obj.Points                              vector<point>
obj.Vg                                  vector<Vector>
obj.Vg[0]                               Vector
obj.Vg[0].w                             double
obj.Vg[0].x                             double
obj.Vg[0].y                             double
obj.Vg[0].z                             double
obj.Vn                                  vector<Vector>
obj.Vn[0]                               Vector
obj.Vn[0].w                             double
obj.Vn[0].x                             double
obj.Vn[0].y                             double
obj.Vn[0].z                             double
obj.Vp                                  vector<Vector>
obj.Vp[0]                               Vector
obj.Vp[0].w                             double
obj.Vp[0].x                             double
obj.Vp[0].y                             double
obj.Vp[0].z                             double
obj.Vt                                  vector<Vector>
obj.Vt[0]                               Vector
obj.Vt[0].w                             double
obj.Vt[0].x                             double
obj.Vt[0].y                             double
obj.Vt[0].z                             double
pieces                                  vector<piecestruc>
port                                    vector<portstruc>
sim_states                              vector<sim_state>
sim_states[0]                           sim_state
sim_states[0].a_att                     double
sim_states[0].a_att_target              double
sim_states[0].agent_name                string
sim_states[0].b_att                     double
sim_states[0].b_att_target              double
sim_states[0].c_att                     double
sim_states[0].c_att_target              double
sim_states[0].d_att                     double
sim_states[0].d_att_target              double
sim_states[0].node_name                 string
sim_states[0].t_acc                     double
sim_states[0].t_att                     double
sim_states[0].t_att_target              double
sim_states[0].t_pos                     double
sim_states[0].t_vel                     double
sim_states[0].target_altitude           double
sim_states[0].target_latitude           double
sim_states[0].target_longitude          double
sim_states[0].x_acc                     double
sim_states[0].x_acc_diff                double
sim_states[0].x_alpha                   double
sim_states[0].x_omega                   double
sim_states[0].x_pos                     double
sim_states[0].x_thrust                  double
sim_states[0].x_torque                  double
sim_states[0].x_vel                     double
sim_states[0].y_acc                     double
sim_states[0].y_acc_diff                double
sim_states[0].y_alpha                   double
sim_states[0].y_omega                   double
sim_states[0].y_pos                     double
sim_states[0].y_thrust                  double
sim_states[0].y_torque                  double
sim_states[0].y_vel                     double
sim_states[0].z_acc                     double
sim_states[0].z_acc_diff                double
sim_states[0].z_alpha                   double
sim_states[0].z_omega                   double
sim_states[0].z_pos                     double
sim_states[0].z_thrust                  double
sim_states[0].z_torque                  double
sim_states[0].z_vel                     double
sim_states[1]                           sim_state
sim_states[1].a_att                     double
sim_states[1].a_att_target              double
sim_states[1].agent_name                string
sim_states[1].b_att                     double
sim_states[1].b_att_target              double
sim_states[1].c_att                     double
sim_states[1].c_att_target              double
sim_states[1].d_att                     double
sim_states[1].d_att_target              double
sim_states[1].node_name                 string
sim_states[1].t_acc                     double
sim_states[1].t_att                     double
sim_states[1].t_att_target              double
sim_states[1].t_pos                     double
sim_states[1].t_vel                     double
sim_states[1].target_altitude           double
sim_states[1].target_latitude           double
sim_states[1].target_longitude          double
sim_states[1].x_acc                     double
sim_states[1].x_acc_diff                double
sim_states[1].x_alpha                   double
sim_states[1].x_omega                   double
sim_states[1].x_pos                     double
sim_states[1].x_thrust                  double
sim_states[1].x_torque                  double
sim_states[1].x_vel                     double
sim_states[1].y_acc                     double
sim_states[1].y_acc_diff                double
sim_states[1].y_alpha                   double
sim_states[1].y_omega                   double
sim_states[1].y_pos                     double
sim_states[1].y_thrust                  double
sim_states[1].y_torque                  double
sim_states[1].y_vel                     double
sim_states[1].z_acc                     double
sim_states[1].z_acc_diff                double
sim_states[1].z_alpha                   double
sim_states[1].z_omega                   double
sim_states[1].z_pos                     double
sim_states[1].z_thrust                  double
sim_states[1].z_torque                  double
sim_states[1].z_vel                     double
sim_states[2]                           sim_state
sim_states[2].a_att                     double
sim_states[2].a_att_target              double
sim_states[2].agent_name                string
sim_states[2].b_att                     double
sim_states[2].b_att_target              double
sim_states[2].c_att                     double
sim_states[2].c_att_target              double
sim_states[2].d_att                     double
sim_states[2].d_att_target              double
sim_states[2].node_name                 string
sim_states[2].t_acc                     double
sim_states[2].t_att                     double
sim_states[2].t_att_target              double
sim_states[2].t_pos                     double
sim_states[2].t_vel                     double
sim_states[2].target_altitude           double
sim_states[2].target_latitude           double
sim_states[2].target_longitude          double
sim_states[2].x_acc                     double
sim_states[2].x_acc_diff                double
sim_states[2].x_alpha                   double
sim_states[2].x_omega                   double
sim_states[2].x_pos                     double
sim_states[2].x_thrust                  double
sim_states[2].x_torque                  double
sim_states[2].x_vel                     double
sim_states[2].y_acc                     double
sim_states[2].y_acc_diff                double
sim_states[2].y_alpha                   double
sim_states[2].y_omega                   double
sim_states[2].y_pos                     double
sim_states[2].y_thrust                  double
sim_states[2].y_torque                  double
sim_states[2].y_vel                     double
sim_states[2].z_acc                     double
sim_states[2].z_acc_diff                double
sim_states[2].z_alpha                   double
sim_states[2].z_omega                   double
sim_states[2].z_pos                     double
sim_states[2].z_thrust                  double
sim_states[2].z_torque                  double
sim_states[2].z_vel                     double
sim_states[3]                           sim_state
sim_states[3].a_att                     double
sim_states[3].a_att_target              double
sim_states[3].agent_name                string
sim_states[3].b_att                     double
sim_states[3].b_att_target              double
sim_states[3].c_att                     double
sim_states[3].c_att_target              double
sim_states[3].d_att                     double
sim_states[3].d_att_target              double
sim_states[3].node_name                 string
sim_states[3].t_acc                     double
sim_states[3].t_att                     double
sim_states[3].t_att_target              double
sim_states[3].t_pos                     double
sim_states[3].t_vel                     double
sim_states[3].target_altitude           double
sim_states[3].target_latitude           double
sim_states[3].target_longitude          double
sim_states[3].x_acc                     double
sim_states[3].x_acc_diff                double
sim_states[3].x_alpha                   double
sim_states[3].x_omega                   double
sim_states[3].x_pos                     double
sim_states[3].x_thrust                  double
sim_states[3].x_torque                  double
sim_states[3].x_vel                     double
sim_states[3].y_acc                     double
sim_states[3].y_acc_diff                double
sim_states[3].y_alpha                   double
sim_states[3].y_omega                   double
sim_states[3].y_pos                     double
sim_states[3].y_thrust                  double
sim_states[3].y_torque                  double
sim_states[3].y_vel                     double
sim_states[3].z_acc                     double
sim_states[3].z_acc_diff                double
sim_states[3].z_alpha                   double
sim_states[3].z_omega                   double
sim_states[3].z_pos                     double
sim_states[3].z_thrust                  double
sim_states[3].z_torque                  double
sim_states[3].z_vel                     double
sim_states[4]                           sim_state
sim_states[4].a_att                     double
sim_states[4].a_att_target              double
sim_states[4].agent_name                string
sim_states[4].b_att                     double
sim_states[4].b_att_target              double
sim_states[4].c_att                     double
sim_states[4].c_att_target              double
sim_states[4].d_att                     double
sim_states[4].d_att_target              double
sim_states[4].node_name                 string
sim_states[4].t_acc                     double
sim_states[4].t_att                     double
sim_states[4].t_att_target              double
sim_states[4].t_pos                     double
sim_states[4].t_vel                     double
sim_states[4].target_altitude           double
sim_states[4].target_latitude           double
sim_states[4].target_longitude          double
sim_states[4].x_acc                     double
sim_states[4].x_acc_diff                double
sim_states[4].x_alpha                   double
sim_states[4].x_omega                   double
sim_states[4].x_pos                     double
sim_states[4].x_thrust                  double
sim_states[4].x_torque                  double
sim_states[4].x_vel                     double
sim_states[4].y_acc                     double
sim_states[4].y_acc_diff                double
sim_states[4].y_alpha                   double
sim_states[4].y_omega                   double
sim_states[4].y_pos                     double
sim_states[4].y_thrust                  double
sim_states[4].y_torque                  double
sim_states[4].y_vel                     double
sim_states[4].z_acc                     double
sim_states[4].z_acc_diff                double
sim_states[4].z_alpha                   double
sim_states[4].z_omega                   double
sim_states[4].z_pos                     double
sim_states[4].z_thrust                  double
sim_states[4].z_torque                  double
sim_states[4].z_vel                     double
target                                  vector<targetstruc>
timestamp                               double
tle                                     vector<Convert::tlestruc>
unit                                    vector<vector<unitstruc>>
unit[0]                                 vector<unitstruc>
unit[0][0]                              unitstruc
unit[0][0].name                         string
unit[0][0].p0                           float
unit[0][0].p1                           float
unit[0][0].p2                           float
unit[0][0].type                         uint16_t
unit[10]                                vector<unitstruc>
unit[10][0]                             unitstruc
unit[10][0].name                        string
unit[10][0].p0                          float
unit[10][0].p1                          float
unit[10][0].p2                          float
unit[10][0].type                        uint16_t
unit[11]                                vector<unitstruc>
unit[11][0]                             unitstruc
unit[11][0].name                        string
unit[11][0].p0                          float
unit[11][0].p1                          float
unit[11][0].p2                          float
unit[11][0].type                        uint16_t
unit[11][1]                             unitstruc
unit[11][1].name                        string
unit[11][1].p0                          float
unit[11][1].p1                          float
unit[11][1].p2                          float
unit[11][1].type                        uint16_t
unit[11][2]                             unitstruc
unit[11][2].name                        string
unit[11][2].p0                          float
unit[11][2].p1                          float
unit[11][2].p2                          float
unit[11][2].type                        uint16_t
unit[12]                                vector<unitstruc>
unit[12][0]                             unitstruc
unit[12][0].name                        string
unit[12][0].p0                          float
unit[12][0].p1                          float
unit[12][0].p2                          float
unit[12][0].type                        uint16_t
unit[12][1]                             unitstruc
unit[12][1].name                        string
unit[12][1].p0                          float
unit[12][1].p1                          float
unit[12][1].p2                          float
unit[12][1].type                        uint16_t
unit[13]                                vector<unitstruc>
unit[13][0]                             unitstruc
unit[13][0].name                        string
unit[13][0].p0                          float
unit[13][0].p1                          float
unit[13][0].p2                          float
unit[13][0].type                        uint16_t
unit[14]                                vector<unitstruc>
unit[14][0]                             unitstruc
unit[14][0].name                        string
unit[14][0].p0                          float
unit[14][0].p1                          float
unit[14][0].p2                          float
unit[14][0].type                        uint16_t
unit[15]                                vector<unitstruc>
unit[15][0]                             unitstruc
unit[15][0].name                        string
unit[15][0].p0                          float
unit[15][0].p1                          float
unit[15][0].p2                          float
unit[15][0].type                        uint16_t
unit[15][1]                             unitstruc
unit[15][1].name                        string
unit[15][1].p0                          float
unit[15][1].p1                          float
unit[15][1].p2                          float
unit[15][1].type                        uint16_t
unit[16]                                vector<unitstruc>
unit[16][0]                             unitstruc
unit[16][0].name                        string
unit[16][0].p0                          float
unit[16][0].p1                          float
unit[16][0].p2                          float
unit[16][0].type                        uint16_t
unit[16][1]                             unitstruc
unit[16][1].name                        string
unit[16][1].p0                          float
unit[16][1].p1                          float
unit[16][1].p2                          float
unit[16][1].type                        uint16_t
unit[17]                                vector<unitstruc>
unit[17][0]                             unitstruc
unit[17][0].name                        string
unit[17][0].p0                          float
unit[17][0].p1                          float
unit[17][0].p2                          float
unit[17][0].type                        uint16_t
unit[18]                                vector<unitstruc>
unit[18][0]                             unitstruc
unit[18][0].name                        string
unit[18][0].p0                          float
unit[18][0].p1                          float
unit[18][0].p2                          float
unit[18][0].type                        uint16_t
unit[19]                                vector<unitstruc>
unit[19][0]                             unitstruc
unit[19][0].name                        string
unit[19][0].p0                          float
unit[19][0].p1                          float
unit[19][0].p2                          float
unit[19][0].type                        uint16_t
unit[1]                                 vector<unitstruc>
unit[1][0]                              unitstruc
unit[1][0].name                         string
unit[1][0].p0                           float
unit[1][0].p1                           float
unit[1][0].p2                           float
unit[1][0].type                         uint16_t
unit[1][1]                              unitstruc
unit[1][1].name                         string
unit[1][1].p0                           float
unit[1][1].p1                           float
unit[1][1].p2                           float
unit[1][1].type                         uint16_t
unit[1][2]                              unitstruc
unit[1][2].name                         string
unit[1][2].p0                           float
unit[1][2].p1                           float
unit[1][2].p2                           float
unit[1][2].type                         uint16_t
unit[1][3]                              unitstruc
unit[1][3].name                         string
unit[1][3].p0                           float
unit[1][3].p1                           float
unit[1][3].p2                           float
unit[1][3].type                         uint16_t
unit[20]                                vector<unitstruc>
unit[20][0]                             unitstruc
unit[20][0].name                        string
unit[20][0].p0                          float
unit[20][0].p1                          float
unit[20][0].p2                          float
unit[20][0].type                        uint16_t
unit[20][1]                             unitstruc
unit[20][1].name                        string
unit[20][1].p0                          float
unit[20][1].p1                          float
unit[20][1].p2                          float
unit[20][1].type                        uint16_t
unit[20][2]                             unitstruc
unit[20][2].name                        string
unit[20][2].p0                          float
unit[20][2].p1                          float
unit[20][2].p2                          float
unit[20][2].type                        uint16_t
unit[21]                                vector<unitstruc>
unit[21][0]                             unitstruc
unit[21][0].name                        string
unit[21][0].p0                          float
unit[21][0].p1                          float
unit[21][0].p2                          float
unit[21][0].type                        uint16_t
unit[22]                                vector<unitstruc>
unit[22][0]                             unitstruc
unit[22][0].name                        string
unit[22][0].p0                          float
unit[22][0].p1                          float
unit[22][0].p2                          float
unit[22][0].type                        uint16_t
unit[23]                                vector<unitstruc>
unit[23][0]                             unitstruc
unit[23][0].name                        string
unit[23][0].p0                          float
unit[23][0].p1                          float
unit[23][0].p2                          float
unit[23][0].type                        uint16_t
unit[23][1]                             unitstruc
unit[23][1].name                        string
unit[23][1].p0                          float
unit[23][1].p1                          float
unit[23][1].p2                          float
unit[23][1].type                        uint16_t
unit[24]                                vector<unitstruc>
unit[24][0]                             unitstruc
unit[24][0].name                        string
unit[24][0].p0                          float
unit[24][0].p1                          float
unit[24][0].p2                          float
unit[24][0].type                        uint16_t
unit[25]                                vector<unitstruc>
unit[25][0]                             unitstruc
unit[25][0].name                        string
unit[25][0].p0                          float
unit[25][0].p1                          float
unit[25][0].p2                          float
unit[25][0].type                        uint16_t
unit[25][1]                             unitstruc
unit[25][1].name                        string
unit[25][1].p0                          float
unit[25][1].p1                          float
unit[25][1].p2                          float
unit[25][1].type                        uint16_t
unit[26]                                vector<unitstruc>
unit[26][0]                             unitstruc
unit[26][0].name                        string
unit[26][0].p0                          float
unit[26][0].p1                          float
unit[26][0].p2                          float
unit[26][0].type                        uint16_t
unit[27]                                vector<unitstruc>
unit[27][0]                             unitstruc
unit[27][0].name                        string
unit[27][0].p0                          float
unit[27][0].p1                          float
unit[27][0].p2                          float
unit[27][0].type                        uint16_t
unit[28]                                vector<unitstruc>
unit[28][0]                             unitstruc
unit[28][0].name                        string
unit[28][0].p0                          float
unit[28][0].p1                          float
unit[28][0].p2                          float
unit[28][0].type                        uint16_t
unit[29]                                vector<unitstruc>
unit[29][0]                             unitstruc
unit[29][0].name                        string
unit[29][0].p0                          float
unit[29][0].p1                          float
unit[29][0].p2                          float
unit[29][0].type                        uint16_t
unit[2]                                 vector<unitstruc>
unit[2][0]                              unitstruc
unit[2][0].name                         string
unit[2][0].p0                           float
unit[2][0].p1                           float
unit[2][0].p2                           float
unit[2][0].type                         uint16_t
unit[2][1]                              unitstruc
unit[2][1].name                         string
unit[2][1].p0                           float
unit[2][1].p1                           float
unit[2][1].p2                           float
unit[2][1].type                         uint16_t
unit[30]                                vector<unitstruc>
unit[30][0]                             unitstruc
unit[30][0].name                        string
unit[30][0].p0                          float
unit[30][0].p1                          float
unit[30][0].p2                          float
unit[30][0].type                        uint16_t
unit[31]                                vector<unitstruc>
unit[31][0]                             unitstruc
unit[31][0].name                        string
unit[31][0].p0                          float
unit[31][0].p1                          float
unit[31][0].p2                          float
unit[31][0].type                        uint16_t
unit[31][1]                             unitstruc
unit[31][1].name                        string
unit[31][1].p0                          float
unit[31][1].p1                          float
unit[31][1].p2                          float
unit[31][1].type                        uint16_t
unit[31][2]                             unitstruc
unit[31][2].name                        string
unit[31][2].p0                          float
unit[31][2].p1                          float
unit[31][2].p2                          float
unit[31][2].type                        uint16_t
unit[32]                                vector<unitstruc>
unit[32][0]                             unitstruc
unit[32][0].name                        string
unit[32][0].p0                          float
unit[32][0].p1                          float
unit[32][0].p2                          float
unit[32][0].type                        uint16_t
unit[33]                                vector<unitstruc>
unit[33][0]                             unitstruc
unit[33][0].name                        string
unit[33][0].p0                          float
unit[33][0].p1                          float
unit[33][0].p2                          float
unit[33][0].type                        uint16_t
unit[34]                                vector<unitstruc>
unit[34][0]                             unitstruc
unit[34][0].name                        string
unit[34][0].p0                          float
unit[34][0].p1                          float
unit[34][0].p2                          float
unit[34][0].type                        uint16_t
unit[34][1]                             unitstruc
unit[34][1].name                        string
unit[34][1].p0                          float
unit[34][1].p1                          float
unit[34][1].p2                          float
unit[34][1].type                        uint16_t
unit[35]                                vector<unitstruc>
unit[35][0]                             unitstruc
unit[35][0].name                        string
unit[35][0].p0                          float
unit[35][0].p1                          float
unit[35][0].p2                          float
unit[35][0].type                        uint16_t
unit[35][1]                             unitstruc
unit[35][1].name                        string
unit[35][1].p0                          float
unit[35][1].p1                          float
unit[35][1].p2                          float
unit[35][1].type                        uint16_t
unit[3]                                 vector<unitstruc>
unit[3][0]                              unitstruc
unit[3][0].name                         string
unit[3][0].p0                           float
unit[3][0].p1                           float
unit[3][0].p2                           float
unit[3][0].type                         uint16_t
unit[4]                                 vector<unitstruc>
unit[4][0]                              unitstruc
unit[4][0].name                         string
unit[4][0].p0                           float
unit[4][0].p1                           float
unit[4][0].p2                           float
unit[4][0].type                         uint16_t
unit[4][1]                              unitstruc
unit[4][1].name                         string
unit[4][1].p0                           float
unit[4][1].p1                           float
unit[4][1].p2                           float
unit[4][1].type                         uint16_t
unit[4][2]                              unitstruc
unit[4][2].name                         string
unit[4][2].p0                           float
unit[4][2].p1                           float
unit[4][2].p2                           float
unit[4][2].type                         uint16_t
unit[4][3]                              unitstruc
unit[4][3].name                         string
unit[4][3].p0                           float
unit[4][3].p1                           float
unit[4][3].p2                           float
unit[4][3].type                         uint16_t
unit[4][4]                              unitstruc
unit[4][4].name                         string
unit[4][4].p0                           float
unit[4][4].p1                           float
unit[4][4].p2                           float
unit[4][4].type                         uint16_t
unit[5]                                 vector<unitstruc>
unit[5][0]                              unitstruc
unit[5][0].name                         string
unit[5][0].p0                           float
unit[5][0].p1                           float
unit[5][0].p2                           float
unit[5][0].type                         uint16_t
unit[5][1]                              unitstruc
unit[5][1].name                         string
unit[5][1].p0                           float
unit[5][1].p1                           float
unit[5][1].p2                           float
unit[5][1].type                         uint16_t
unit[5][2]                              unitstruc
unit[5][2].name                         string
unit[5][2].p0                           float
unit[5][2].p1                           float
unit[5][2].p2                           float
unit[5][2].type                         uint16_t
unit[5][3]                              unitstruc
unit[5][3].name                         string
unit[5][3].p0                           float
unit[5][3].p1                           float
unit[5][3].p2                           float
unit[5][3].type                         uint16_t
unit[6]                                 vector<unitstruc>
unit[6][0]                              unitstruc
unit[6][0].name                         string
unit[6][0].p0                           float
unit[6][0].p1                           float
unit[6][0].p2                           float
unit[6][0].type                         uint16_t
unit[7]                                 vector<unitstruc>
unit[7][0]                              unitstruc
unit[7][0].name                         string
unit[7][0].p0                           float
unit[7][0].p1                           float
unit[7][0].p2                           float
unit[7][0].type                         uint16_t
unit[7][1]                              unitstruc
unit[7][1].name                         string
unit[7][1].p0                           float
unit[7][1].p1                           float
unit[7][1].p2                           float
unit[7][1].type                         uint16_t
unit[8]                                 vector<unitstruc>
unit[8][0]                              unitstruc
unit[8][0].name                         string
unit[8][0].p0                           float
unit[8][0].p1                           float
unit[8][0].p2                           float
unit[8][0].type                         uint16_t
unit[9]                                 vector<unitstruc>
unit[9][0]                              unitstruc
unit[9][0].name                         string
unit[9][0].p0                           float
unit[9][0].p1                           float
unit[9][0].p2                           float
unit[9][0].type                         uint16_t
unit[9][1]                              unitstruc
unit[9][1].name                         string
unit[9][1].p0                           float
unit[9][1].p1                           float
unit[9][1].p2                           float
unit[9][1].type                         uint16_t
user                                    vector<userstruc>
vertexs                                 vector<vertexstruc>`;

export default testraw;
